### ISSUE TITLE
Fix O(n) functions match_next and match_prev

### ISSUE THREAD

**Issue by RuolinZheng08** [cmsc22000-project-2018/fulltext#131]
Modify the two functions so they give O(1) access.
Relying on the fact that lists are doubly linked.

**Comment by RuolinZheng08** [comment]
As Max had fixed both functions on max/sh, this will be handled in future merges into dev / master

**Comment by MoldyAppleJuice** [comment]
Update: because `simclist` is singly linked, there is no way to perform an O(1) `match_prev()`. However, it is possible to make `match_next()` O(1). 
Requires:
- starting an iteration session in search.c
- calling `list_iterator_next()` in match.c
- ending iteration session in search.c before ftsh exits
- need to check if going backwards in the list will properly affect where the pointer is.

**Comment by mpcsh** [comment]
Hey, from my knowledge of `simclist`'s internals, the answer to that last point is that it will definitely not move the iteration session's pointer. I actually now don't think this is possible given that I've painted us into a corner with `simclist`. It's up to y'all whether you want to leave things O(n) or go back to `GList`.

**Comment by MoldyAppleJuice** [comment]
Haha ok, we're sticking with the current state of match.c (`match_next` and `match_prev` as O(n), taking an index and match list)
