### ISSUE TITLE
Write Unit Tests for find_match_trie in search.c

### ISSUE THREAD

**Issue by RuolinZheng08** [cmsc22000-project-2018/fulltext#140]
Test the function's correctness for every word in a normal trie and possible bad trie inputs.

**Comment by MoldyAppleJuice** [comment]
[4f65e19]
- removed references `match_remove()`
- updated tests for `match_next()` and `match_prev()` to take index instead of pointer to match
- removed `#includes "simclist.c" from match.c, edited Makefiles
- added test_search.c from ruolin/unit-tests-search

[766ba61]
- refactored existing tests for single word searches (`char*`) to search using a `trie_t*`
- added test that uses `trie_t*` with multiple strings, in a line with multiple occurances 

Need to do:
- refactor existing tests to test the match_list

**Comment by MoldyAppleJuice** [comment]
[4f0ee1f] refactored tests to test the match list. with the use of tries. some tests no passing (commented out)
